# Generated by Django 3.2.12 on 2022-08-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('required_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('robot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exp', models.IntegerField()),
                ('level', models.ForeignKey(db_column='level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots', to='bobi.level')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gas', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('battery', models.FloatField()),
                ('robot_id', models.ForeignKey(db_column='robot_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='bobi.robot')),
            ],
        ),
    ]
