# Generated by Django 3.2.12 on 2022-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='narr_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
