# Generated by Django 3.2.12 on 2022-08-08 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('voice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('voice_link', models.CharField(max_length=100)),
                ('user_send', models.BooleanField()),
                ('is_checked', models.BooleanField()),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
