# Generated by Django 3.2.12 on 2022-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='datetime',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
