# Generated by Django 3.2.12 on 2022-08-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobi', '0002_alter_sensor_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='level',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='robot_id',
        ),
    ]
