# Generated by Django 3.2.12 on 2022-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_auto_20220816_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=30, null=True)),
                ('is_checked', models.BooleanField()),
            ],
        ),
    ]
