# Generated by Django 3.2.12 on 2022-08-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
