# Generated by Django 3.2.12 on 2022-08-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220804_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='robot_id',
        ),
    ]
