# Generated by Django 3.2.12 on 2022-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
