# Generated by Django 3.2.12 on 2022-08-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_archiveimage_archivevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveimage',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='archivevideo',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
    ]
