# Generated by Django 3.2.12 on 2022-08-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobi', '0004_sensor_robot_id'),
        ('accounts', '0003_remove_user_robot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='robot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bobi.robot'),
        ),
    ]
