# Generated by Django 3.2.12 on 2022-08-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobi', '0005_robot_level'),
        ('accounts', '0004_user_robot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('youtube_id', models.CharField(max_length=30, null=True)),
                ('nickname', models.CharField(max_length=10, null=True)),
                ('robot_id', models.ForeignKey(db_column='robot_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bobi.robot')),
            ],
        ),
    ]
