# Generated by Django 3.2.12 on 2022-08-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobi', '0004_sensor_robot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='level',
            field=models.ForeignKey(db_column='level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots', to='bobi.level'),
        ),
    ]
