# Generated by Django 3.2.12 on 2022-08-08 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('archive_id', models.IntegerField(primary_key=True, serialize=False)),
                ('img_link', models.CharField(max_length=100)),
                ('youtube_link', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=20)),
                ('contents', models.TextField(max_length=200)),
                ('id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
